name             'install'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures install'
long_description 'Installs/Configures install'
version          '0.1.0'

depends 'docker', '~> 1.0'
depends 'git', '~> 4.3.4'
